# Podman Compose deployment of @@CONTAINER_NAME@@ (ROCm, Strix Halo).
#
# One of the file-based deployment methods — the Makefile (`make deploy`),
# this file, and the quadlet units all define the identical container
# (name, image, port 8000, devices, IPC, volumes, env). Generated by
# `init.sh` from the shared submodule; kept in lockstep with
# TAGS by `make sync`. Run exactly ONE method at a time:
#
#   podman compose up -d              # start (recreates if changed)
#   podman compose down               # stop & remove
#   podman compose logs -f @@CONTAINER_NAME@@

secrets:
  huggingface-token:
    external: true

services:
  @@CONTAINER_NAME@@:
    image: ${IMAGE:-localhost/llamacpp:@@IMAGE_TAG@@}
    container_name: ${CONTAINER_NAME:-@@CONTAINER_NAME@@}
    # Custom code to enable ipc: host in podman-compose. See the family notes.
    ipc: host
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    devices:
      - /dev/dri
      - /dev/kfd
    group_add:
      - video
      - render
    security_opt:
      - seccomp=unconfined
    secrets:
      - source: huggingface-token
        type: env
        target: HF_TOKEN
    volumes:
      - @@HOME_DIR@@/.cache/huggingface/hub/:/root/.cache/huggingface/hub/:Z
      - @@HOME_DIR@@/.config/llama.cpp/:/root/.config/llama.cpp/:Z
    environment:
      # Model
      LLAMA_ARG_HF_REPO: "@@MODEL@@"
      LLAMA_ARG_ALIAS: "@@ALIAS@@"
      # Server
      LLAMA_ARG_LOG_TIMESTAMPS: "on"
      LLAMA_ARG_HOST: "0.0.0.0"
      LLAMA_ARG_PORT: "8000"
      # Runtime
      LLAMA_ARG_THREADS: "8"
      LLAMA_ARG_LOAD_MODE: "auto"
      LLAMA_ARG_FIT: "off"
      LLAMA_ARG_N_GPU_LAYERS: "99"
      LLAMA_ARG_CTX_SIZE: "262144"
      LLAMA_ARG_FLASH_ATTN: "on"
      LLAMA_ARG_N_PARALLEL: "1"
      LLAMA_ARG_CONT_BATCHING: "on"
      LLAMA_ARG_SPEC_TYPE: "draft-mtp"
      LLAMA_ARG_CACHE_TYPE_K: "q8_0"
      LLAMA_ARG_CACHE_TYPE_V: "q8_0"
      # Features
      LLAMA_ARG_UI: "on"
      LLAMA_ARG_UI_MCP_PROXY: "on"
      LLAMA_ARG_AGENT: "on"
      LLAMA_ARG_TOOLS: "all"
      LLAMA_ARG_REASONING: "on"
      LLAMA_ARG_REASONING_EFFORT: "medium"
      LLAMA_ARG_JINJA: "on"
