# llamacpp-@@CONTAINER_NAME@@ — immutable project identity.
#
# Generated by `make init` from templates/PROJECT.tpl. This file names the ONE
# model this project serves, and it is set exactly once: a project serves one
# model for its lifetime, and the container name, image name and alias are all
# derived from it. No make target ever rewrites this file — to serve a different
# model, initialize a brand-new project (git init + git submodule add + make init).
#
# Version keys (LLAMA_TAG / ROCM_VERSION / FEDORA_VERSION) live in TAGS and are
# managed by the shared submodule via `make sync-versions`.

MODEL=@@MODEL@@
