# llamacpp-@@CONTAINER_NAME@@ — immutable project identity.
#
# Generated by `init.sh` from templates/PROJECT.tpl. This file names the ONE
# model this project serves, and it is set exactly once: a project serves one
# model for its lifetime. CONTAINER_NAME (the systemd service + container name)
# is derived from the model and stored here so the shared Makefile can find the
# quadlet units; the image is a shared, GENERIC image (localhost/llamacpp) whose
# model is configured at runtime, so it is NOT derived from the model. No make
# target ever rewrites this file — to serve a different model, initialize a
# brand-new project (git init + git submodule add + bash shared/init.sh).
#
# Version keys (LLAMA_TAG / ROCM_VERSION / FEDORA_VERSION) live in TAGS and are
# managed by the shared submodule via `make sync-versions`.

MODEL=@@MODEL@@
CONTAINER_NAME=@@CONTAINER_NAME@@
