# llamacpp-@@CONTAINER_NAME@@ — version source of truth (managed by the submodule).
#
# Generated by `init.sh` from the shared submodule. The image tag is
# computed by the Makefile (never hand-typed):
#
#     IMAGE_TAG = <LLAMA_TAG>-rocm-<ROCM_VERSION>
#
# LLAMA_TAG / ROCM_VERSION / FEDORA_VERSION are managed by the shared submodule
# (`make sync-versions` pulls them from shared/TAGS). The served model lives in
# the PROJECT file, not here.

IMAGE_NAME=localhost/@@CONTAINER_NAME@@
LLAMA_TAG=@@LLAMA_TAG@@
ROCM_VERSION=@@ROCM_VERSION@@
FEDORA_VERSION=@@FEDORA_VERSION@@
