# llamacpp-@@CONTAINER_NAME@@ — single source of truth for image build & deployment.
#
# Generated by `make init` from the llamacpp-shared submodule. The image tag is
# computed by the Makefile (never hand-typed):
#
#     IMAGE_TAG = <LLAMA_TAG>-rocm-<ROCM_VERSION>
#
# LLAMA_TAG / ROCM_VERSION / FEDORA_VERSION are managed by the shared submodule
# (`make sync-versions` pulls them from shared/TAGS). MODEL is this project's
# one-time model input — a project serves exactly one model and never changes it.

IMAGE_NAME=localhost/@@CONTAINER_NAME@@
LLAMA_TAG=@@LLAMA_TAG@@
ROCM_VERSION=@@ROCM_VERSION@@
FEDORA_VERSION=@@FEDORA_VERSION@@
MODEL=@@MODEL@@
